site/config.toml

Correction to base url

---

.github/workflows/github-pages.yaml

fix generate docs command

---

packages/common/Makefile

The init section was overwritten and some tools didn't install properly﻿

Fixed Makefile for common module

---

site/content/en/docs/Getting started/installation.md

* point to github repo releases for dlownload
* substitute `$HOME` for `~`

update download and unzip instructions

---

packages/cdk/package-lock.json
packages/cdk/package.json

Updating CDK and dependencies versions.

Bumping up dependencies versions

---

site/config.toml
site/content/en/community/_index.md

Added Gitter links to config and Community

Added Gitter links

---

.github/workflows/notify.yml

Adding a workflow to notify us on Slack when a PR is opened. This just covers the basics to get us going.
I tested the workflow against my own repository and slack channel.

Create Notify Workflow

---

CONTRIBUTING.md

Fix typo in licensing link

---

packages/cli/cmd/application/description.go
site/content/en/docs/Getting started/installation.md

*Description of changes:* Removing an extra emoji that was initially brought in.

Remove Extra Emoji

---

packages/cli/internal/pkg/cli/logs_core.go
site/content/en/docs/Tutorials/walkthrough.md

Adding more information on how to use the filter flag in the `logs` command.

Improve logs filter documentation

---

examples/nf-core-project/README.md
examples/nf-core-project/agc-project.yaml
examples/nf-core-project/workflows/atacseq/MANIFEST.json
examples/nf-core-project/workflows/atacseq/design.csv
examples/nf-core-project/workflows/atacseq/inputs.json
examples/nf-core-project/workflows/rnaseq/MANIFEST.json
examples/nf-core-project/workflows/rnaseq/inputs.json
examples/nf-core-project/workflows/sarek/MANIFEST.json
examples/nf-core-project/workflows/sarek/inputs.json

Project with 3 workflows from nf-core

add nf-core-project

---

README.md

Add node install instruction to README

Add node install instruction to README

---

packages/cli/internal/pkg/aws/batch/get_jobs.go
packages/cli/internal/pkg/aws/cdk/clear_context.go
packages/cli/internal/pkg/aws/cdk/deploy_app.go
packages/cli/internal/pkg/aws/cdk/destroy_app.go
packages/cli/internal/pkg/aws/cdk/execute_cdk.go
packages/cli/internal/pkg/aws/cfn/delete_stack.go
packages/cli/internal/pkg/aws/cfn/get_stack_exports.go
packages/cli/internal/pkg/aws/cfn/get_stack_status.go
packages/cli/internal/pkg/aws/cfn/list_stacks.go
packages/cli/internal/pkg/aws/cwl/get_logs.go
packages/cli/internal/pkg/aws/cwl/stream_logs.go
packages/cli/internal/pkg/aws/ddb/get_workflow_instance_by_id.go
packages/cli/internal/pkg/aws/ddb/list_workflow_instances.go
packages/cli/internal/pkg/aws/ddb/list_workflow_instances_by_context.go
packages/cli/internal/pkg/aws/ddb/list_workflow_instances_by_name.go
packages/cli/internal/pkg/aws/ddb/list_workflows.go
packages/cli/internal/pkg/aws/ddb/write_workflow_instance.go
packages/cli/internal/pkg/aws/ecr/image_listable.go
packages/cli/internal/pkg/aws/ecr/image_reference.go
packages/cli/internal/pkg/aws/s3/bucket_exists.go
packages/cli/internal/pkg/aws/s3/sync_file.go
packages/cli/internal/pkg/aws/s3/upload_file.go
packages/cli/internal/pkg/aws/sts/get_account.go
packages/cli/internal/pkg/cli/actionable/error.go
packages/cli/internal/pkg/cli/actionable/error_test.go
packages/cli/internal/pkg/cli/actionable/mappings.go

This change adds actionable suggestions for known issues when querying AWS. This enables AGC users to be able to quickly resolves issues when they occur and can be extended by adding more values to the map.
Related PR: https://github.com/aws/amazon-genomics-cli/pull/33
Example logs (spacing between commands is added by me for clarity)
```
38f9d35245b9:local elliotsm$ ./agc context status
2021-09-28T16:06:52-07:00 ✘   error="operation error CloudFormation: ListStacks, https response error StatusCode: 403, RequestID: b3fbcf00-9c9d-4d79-9f35-07f9bce403ae, api error InvalidClientTokenId: The security token included in the request is invalid"
Error: an error occurred invoking 'context status'
with variables: <nil>
caused by: operation error CloudFormation: ListStacks, …
```

Adds AWS generic actionable errors

---

THIRD-PARTY
buildspec.yml

* Add license and third-party files to the release zip file
* Clean up some minor formatting issues in the third-party file﻿

Add license and attribution to zip file

---

packages/cdk/lib/roles/cromwell-adapter-role.ts
packages/cdk/lib/roles/cromwell-engine-role.ts
packages/cdk/lib/roles/nextflow-adapter-role.ts
packages/cdk/lib/roles/policies/nextflow-describe-jobs-batch-policy.ts
packages/cdk/lib/roles/policies/nextflow-submit-job-batch-policy.ts
packages/cdk/lib/stacks/nested/batch-stack.ts
packages/cdk/lib/stacks/nested/cromwell-engine-stack.ts
packages/cdk/lib/stacks/nested/nextflow-engine-stack.ts

**Description**
Removed unnecessary permissions from adapter role, and minimized permissions that it requires for both Cromwell and Nextflow.
**Testing**
All code tested by running `make`
Cromwell code tested by running `bam-to-unmapped-bams`
Nextflow code tested by running `hello`

Ahmaalba/Adapter Role Least Privilege Design

---

.github/workflows/codeql-analysis.yml

Detects common vulnerabilities and coding errors. This is maintained by Github.

CodeQL Security Analysis

---

extras/agc-minimal-permissions/package-lock.json
extras/agc-minimal-permissions/package.json

Updated CDK and corresponding npm dependencies in `extras/agc-minimal-permissions` CDK package to remove dependencies with known vulnerabilities.
```
@aws-cdk/assert       1.98.0  →   1.126.0     
@types/jest         ^26.0.10  →   ^27.0.2     
@types/node         10.17.27  →   16.10.3     
jest                 ^26.4.2  →   ^27.2.4     
ts-jest              ^26.2.0  →   ^27.0.5     
ts-node               ^9.0.0  →   ^10.2.1     
typescript            ~3.9.7  →    ~4.4.3     
@aws-cdk/aws-iam    ^1.121.0  →  ^1.126.0     
@aws-cdk/core        ^1.98.0  →  ^1.126.0     
source-map-support   ^0.5.16  →   ^0.5.20   
```
[//]: # …

update extras dependencies

---

site/content/en/docs/Getting started/prerequisites.md

Updates a TODO comment in the documentation with a pointer on how to generate the minimal set of permissions
**Checklist**
----

Updates the workflow documentation to include reference to a protocol

---

site/README.md

Just me being pedantic
Signed-off-by: Sean Smith <seaam@amazon.com>
----

Cleaned up docs README

---

.github/PULL_REQUEST_TEMPLATE.md

Update Pull Request Template to Follow Conventional Commits
Tested on forked repo.
**Checklist**
----

chore: Update Pull Request Template to Follow Conventional Commits

---

.github/semantic.yml

Add semantics behavior overrides to only check title of the PR for conventional commit standard. 
Tested on forked repo. 
**Checklist**
----

ci: Add semantic behavior overrides

---

site/content/en/docs/Getting started/helloworld.md

the context name in `/examples/demo-wdl-project` is `myContext`, which is used by the examples here.
**Checklist**
----

fix: Use correct context name

---

packages/cli/internal/pkg/environment/environment.go
scripts/run-dev.sh

Updating AGC to use the latest released versions of our workflow engines and WES adapter.
I ran AGC against the example cromwell and nextflow 'hello' workflows - both deployed and ran to completion.
**Checklist**
----

build: use latest build images

---

site/content/en/docs/Concepts/accounts.md

fix: correctly link to core app

---

examples/gatk-best-practices-project/gatk4-rnaseq-germline-snps-indels/gatk4-rnaseq-germline-snps-indels.wdl

The `gatk4-rnaseq-germline-snps-indels` workflow revealed a possible bug in miniwdl where it doesn't correctly handle string interpolation of optional values used in a calculation. This change to the workflow works around the problem in miniwdl
In a context with a miniwdl engine:
* `agc workflow run -c spotCtx gatk4-rnaseq-germline-snps-indels`
**Checklist**
----

fix: interpolation work around for miniwdl

---

examples/gatk-best-practices-project/README.md
examples/nf-core-project/README.md

Added information about inputs and typical run times for gatk-best practices and nf-core workflows
N/A
**Checklist**
- [*] If this change would make any existing documentation invalid, I have included those updates within this PR
- [*] Title of this Pull Request follows Conventional Commits standard: https://www.conventionalcommits.org/en/v1.0.0/
----

docs: Add information about example inputs and runtimes

---

site/content/en/docs/Concepts/contexts.md

Added docs section about ongoing cost of idle contexts.
N/A
**Checklist**
----

docs: ongoing cost details

---

site/content/en/docs/Getting started/installation.md

#160 
Corrected install instructions to match new zip format
Downloaded zip and installed.
**Checklist**
----

docs: fix for installation.md

---

packages/cli/Makefile

Our new release process doesn't immediately tag the release commit, causing our versioning logic in build to fallback to the previous tag. The new version line looks to `version.json` as its source of truth.
Git describe adds "the number of additional commits ("14") and an abbreviated object name for the commit itself ("2414721") at the end" [source](https://git-scm.com/docs/git-describe).
Old:
```
$ agc --version
agc version: 1.0.1-1-gfd7b94a
```
New:
```
$ ./packages/cli/bin/local/agc --version
agc version: 1.0.1
```
The version script appears to be unaffected:
~/.agc/.version_cache
```json
{"CurrentVersion":"1.0.1","Versions":[{"Name":"1.0.1","Deprecated":false,"DeprecationMessage":"","Highlig …
```

build: update version lookup logic

---

examples/gatk-best-practices-project-miniwdl/agc-project.yaml

The example GATK workflows on miniwdl project had a project name of "GATK" which collides with the equivalent example project for Cromwell.
* `agc context validate`
* `agc context deploy`
**Checklist**
----

fix: unique project name

---

CHANGELOG.md

ci: Correct CHANGELOG format

---

packages/cdk/lib/constructs/engines/miniwdl/miniwdl-engine.ts

Increased memory allocation for miniwdl to 4096 MiB
* `make test`
* `agc context deploy miniwdlCtx`
* Run a workflow.
* Verify memory allocation of generated job definition in console.
**Checklist**
- [*] I have linted my code before raising the PR
- [*] Title of this Pull Request follows Conventional Commits standard: https://www.conventionalcommits.org/en/v1.0.0/
----

perf: Increased RAM allocation for miniwdl engine

---

.github/workflows/github-pages.yaml

Our docs are set to run against `release` but don't publish unless run on `main`
Changed to publish on release branch
I have not tested these changes.
**Checklist**
----

docs: Publish on release branch

---

packages/cli/internal/pkg/aws/cdk/progress.go

Current implementation of a progress bar had some issues with stability and accuracy, so we decided to switch to a spinner.
- make
- unit tests
- manual test
**Checklist**
----

fix: switch from a progress bar to a spinner

---

README.md

Issue #, if available: #232
I've added the command I had to run to install the version of Go that is needed for AGC, using goenv.
This is the command I ran. After I ran it (with goenv installed in the shell), `make init` started working, and `go version` reported the version that `.go-version` specified.
**Checklist**
This isn't really applicable; the docs aren't under test.
This isn't applicable; no code is modified.
----
*By submitting this pull request, I confirm that my contribution is made under the terms of the …

docs: Tell users to install the right Go to fix #232

---

scripts/package-release.sh

Add publish nightly build to GitHub as part of CI/CD. 
`make release`
**Checklist**
----

ci: Add publish nightly build to GitHub

---

packages/cdk/lib/constants.ts

Currently, our service is unable to perform a retry if a dependency is installed as part of the launch template. This change enables this with some backoffs so that we can retry the functionality shortly afterwards.
NB: The Launch template was unable to interpret if statements, functions and while loops. Because of this I have duplicated the logic manually. Since we aren't guaranteed to see the logs, its an unlikely event from my testing, I am unable to verify why they aren't supported.
deploy context and running a workflow
**Checklist**
----

fix: Creates an automatic retry with back-offs for server dependencies

---

packages/cli/internal/pkg/cli/context/manager.go

We publish ECR artifacts to `us-west-2` and replicate in `us-east-1`. By default, AGC always pulls images from `us-east-1`. However, some customers in global regions outside of US have restrictions on pulling containers from outside regions (e.g. us-east-1). 
As part of this change, we will replicate the assets to every AWS commercial region and pull from whatever region the customer runs AGC in. 
Tested locally with different AWS regions and it's able to fetch the assets from the correct location/region.
[//]: #  (A description of you validated your changes and any relevant logs that show your …

feat: Enable hosting assets in AWS commercial regions

---

packages/cli/internal/pkg/aws/cdk/progress.go
packages/cli/internal/pkg/aws/cdk/progress_test.go

This change implements proper handling of CDK command errors and log.
Before this change:
```
$ agc context deploy ctx1
2021-12-28T10:00:00-08:00 𝒊  Deploying context(s)
Deploying resources for context(s) [ctx1] [---o] 9.2s                                                                                                                                        2021-12-28T10:00:11-08:00 𝒊  Successfully deployed context(s) [ctx1]
$ agc context status
2021-12-28T10:00:22-08:00 𝒊  There are no contexts …
```

fix: Handle errors from CDK command

---

packages/cdk/apps/context/app.ts
packages/cdk/apps/core/app.ts
packages/cdk/lib/constants.ts
packages/cdk/lib/env/context-app-parameters.ts
packages/cli/internal/pkg/cli/account_activate.go
packages/cli/internal/pkg/cli/account_activate_test.go
packages/cli/internal/pkg/cli/context/context_environment.go
packages/cli/internal/pkg/cli/context/manager_deploy_test.go

fixes: #242 
Adds an `agc-version` tag to all AGC-created AWS resources.
I ran `account activate` and `context deploy` commands and confirmed the AWS resources are appropriately tagged with the version (`1.1.2`).
**Checklist**
----

feat: Tag AGC AWS resources with CLI version

---

examples/nf-core-project/agc-project.yaml

fixes: #188 
Sarek and atacseq workflows read from files in the `healthai-public-assets-us-east-1` bucket but don't have read permissions to access it.
Reran workflows, confirmed they didn't error out in the first 30 minutes.
**Checklist**
----

fix: Add AGC assets bucket to project read list

---

packages/cli/cmd/application/main.go

This change lets AGC CLI to print a link to upgrade instructions when new version of AGC is available and/or when a version is marked deprecated. 
```
dzl@88665a545034 demo-wdl-project % agc workflow list
2022-01-03T15:01:47-08:00 𝒊  New version of agc available. Current version is '1.0.1'. The latest version is '1.1.2'. Please consider upgrading to the latest version by following https://aws.github.io/amazon-genomics-cli/docs/getting-started/installation/
2022-01-03T15:01:47-08:00 𝒊  Listing workflows.
WORKFLOWNAME	haplotype
WORKFLOWNAME	hello
WORKFLOWNAME	read
WORKFLOWNAME	words-with-vowels
``` …

docs: Improve upgrade instruction when new version of AGC is available

---

packages/cli/internal/pkg/cli/context_describe.go
packages/cli/internal/pkg/cli/context_describe_test.go
packages/cli/internal/pkg/cli/describe_output_test.go
packages/cli/internal/pkg/cli/types/context.go
site/content/en/docs/Tutorials/walkthrough.md

fixes #220 
Add the WES API endpoint url for a context as part of the output from `agc context describe <context-name>`
Before Change:
```
demo-wdl-project % agc context describe spotCtx          
2022-01-03T22:20:23-08:00 𝒊  Describing context 'spotCtx'
CONTEXT	256	spotCtx	true	STARTED	
OUTPUTLOCATION	s3://agc-586466483460-us-east-2/project/Demo/userid/dzl3501BW/context/spotCtx
```
After Change:
```
demo-wdl-project % agc context describe spotCtx        
2022-01-03T22:20:23-08:00 𝒊  Describing context 'spotCtx'
CONTEXT	256	spotCtx	true	STARTED	
OUTPUTLOCATION	s3://agc-586466483460-us-east-2/project/Demo/userid/dzl3501BW/context/spotCtx
WESENDPOINT	https://k5jirhe0rk.execute-api.us-east-2.amazonaws.com/prod/ga4gh/wes/v1
```
[//]: #  (A …

feat: Add WES API endpoint information to agc context describe output

---

packages/engines/new-engine-template/<engine-name>.aws.sh
packages/engines/new-engine-template/DEVELOPMENT.MD
packages/engines/new-engine-template/Dockerfile
packages/engines/new-engine-template/THIRD-PARTY
packages/engines/new-engine-template/buildspec.yml
packages/engines/snakemake/.gitignore
packages/engines/snakemake/Dockerfile
packages/engines/snakemake/LICENSE
packages/engines/snakemake/README.md
packages/engines/snakemake/THIRD-PARTY
packages/engines/snakemake/buildspec.yml
packages/engines/snakemake/snakemake.aws.sh

These changes add a base AWS Batch image for the snakemake engine to be used by agc as we develop this feature. 
* These changes were tested in our internal respository before being committed to here. 
**Checklist**
- [Y] If this change would make any existing documentation invalid, I have included those updates within this PR
- [Y ] Title of this Pull Request follows Conventional Commits standard: https://www.conventionalcommits.org/en/v1.0.0/
----

feat: Add snakemake base image and template for new engines

---

packages/engines/snakemake/Dockerfile
packages/engines/snakemake/buildspec.yml

This builds snakemake from an internal fork of the snakemake library with modifications made to function on aws-batch. 
This code is temporary and will be removed once snakemake accepts a PR of our executor. 
Validated by running a test workflow using the image. 
**Checklist**
- [Y] If this change would make any existing documentation invalid, I have included those updates within this PR
- [Y] Title of this Pull Request follows …

refactor: Build snakemake from internal fork

---

packages/cdk/lib/artifacts/batch-artifacts/ecs-additions/get-amazon-ebs-autoscale.sh

Users were seeing ebs volumes not being mounted sporadically. This must come from either the script failing to download and/or execute ebs-autoscaling. 
Validated by deploying agc to my personal account and updating the `get-amazon-ebs-autoscale.sh` in my s3 bucket to include this new code. I then validated via ec2 system logs that we were successfully seeing the new code:
```
[   28.504624] cloud-init[3796]: + local s3_path=s3://agc-987650158744-us-west-2/batch-artifacts/amazon-ebs-autoscale.tgz
[   28.504905] …
```

fix: Added retries to ebs-autoscaling download script (resolves #186)

---

packages/engines/snakemake/buildspec.yml

…f snakemake
This adds the ability to login to our repository and pull the required image to build snakemake from our internal forked repository. 
* Validated changed by using this code against a pipeline in my personal aws account. Verified that pipeline could build against my internal repository when combined with CR to internal pipeline code. 
**Checklist**
- [Y] If this change would make any existing documentation invalid, I have included those updates within this PR
- [N/A] I have added unit …

fix: Fixed snakemake buildspec to have permissions to pull from agc-snakemake ecr

---

README.md
site/content/en/docs/Getting started/installation.md

Updated the documentation on the new location of the nightly build. 
`make`
**Checklist**
----

docs: Update nightly build location

---

README.md

* Was having a lot of trouble building locally when running `make init` and `make` with my local build dependencies with latest mainline change
* Was fixed by simply running `go clean --cache` in the project root to have a clean build
* Added `go clean --cache` in README for resolving build issues related to go build/make
`make init` and `make`
**Checklist**
----

docs: add go clean cache in README for resolving build issues

---

examples/demo-wdl-project/workflows/read/README.md

Added README.md file into the demo-wdl read workflow folder. This workflow fails if the input file is not provided, and the README file explain to the end user how to properly set such input file. 
Run read workflow following the instructions in the README file and verified workflow completes successfully.
**Checklist**
----

docs: Added README file for demo-wdl read workflow

---

examples/demo-wdl-project/workflows/haplotype/haplotypecaller-gvcf-gatk4.wdl
examples/demo-wdl-project/workflows/hello/hello.wdl
examples/demo-wdl-project/workflows/read/main.wdl
examples/demo-wdl-project/workflows/words/words-with-vowels.wdl

Added workflow retries to demo-wdl-project
Deploy cromwell context. Run demo-wdl-project workflows, ensure batch job definition has expected number of retries configured.
**Checklist**
----

feat: added workflow retries to demo-wdl-project

---

packages/wes_adapter/Makefile
packages/wes_adapter/README.md
packages/wes_adapter/init-local-server.sh
packages/wes_adapter/install.sh
packages/wes_adapter/start-local-server.sh

To prevent different/incompatible version of python used to build wes adapter for lambda (lambda uses fixed version 3.9), this change makes script install dependencies using python3.9 on release.
Validation was done by running CodeBuild to simulate release pipeline. This is to make sure shell commands work locally and on pipeline, specifically existence of python3.9
```
agent_1  | [Container] 2022/02/01 08:42:28 Phase complete: BUILD State: SUCCEEDED
agent_1  | [Container] 2022/02/01 08:42:28 …
```

fix: use fixed python 3.9 in wes adapter

---

README.md
scripts/run-dev.sh

Fix dev-run.sh by adding the wes_adapter build step
Updated readme and have another option to run local build agc
Ran dev-run.sh, `account activate`, `context deploy`, `run workflow`
```
$ agc account activate
2022-02-04T14:34:56-08:00 𝒊  Activating AGC with bucket '' and VPC ''
Bootstrapping CDK... [--o-] 13s
Activating account... [-o--] 2m30s                                                                              $ agc context deploy myContext
2022-02-04T14:45:33-08:00 𝒊  Deploying …
```

fix: add build wes adapter step to run dev script and readme

---

packages/cdk/npm-shrinkwrap.json
packages/cli/internal/pkg/mocks/io/interfaces.go
packages/cli/internal/pkg/mocks/io/mock_interfaces.go
packages/cli/internal/pkg/osutils/utils.go
packages/cli/internal/pkg/osutils/utils_test.go

Currently our copy mechanism doesn't properly copy over sub-directories over due to an invalid assumption about the file name that was made. This PR changes that logic so that it matches the real world representation of it. This PR also tests some of the "EnsureDirExistence" function now as well.
Tested with multiple files that existed in the current directory and sub-directories and they where all copied over. 
**Checklist**
----

fix: Fixes the mechanism for copying the directory contents

---

examples/gatk-best-practices-project-miniwdl/agc-project.yaml
examples/gatk-best-practices-project/agc-project.yaml
site/content/en/docs/Concepts/projects.md

corrected prefix data paths to include /* at the end so IAM permissions are correctly constructed.
* inspect IAM roles generated
**Checklist**
----

fix: Fix project data path prefix and docs

---

.github/workflows/codeql-analysis.yml
packages/cdk/lib/artifacts/batch-artifacts/ecs-additions/awscli-shim.sh

We recently had some code committed in that looked correctly but due to how bash operates was logically incorrect. This was not picked up by either of the reviewers. As a result, I have included a new github action that runs shellcheck to validate our commands as part of a PR (see the description for examples of this running in my cloned repo).
This should not be merged in until after the next release.
I have run this as an action on my local account.
PR: https://github.com/elliot-smith/amazon-genomics-cli/pull/11
Failed command (which is now fixed in mainline): https://github.com/elliot-smith/amazon-genomics-cli/runs/5222908573?check_suite_focus=true 
**Checklist**
----
*By submitting this pull …

chore: run shellcheck on the main branch

---

examples/demo-snakemake-project/agc-project.yaml
examples/demo-snakemake-project/workflow/countries/LICENSE
examples/demo-snakemake-project/workflow/countries/MANIFEST.json
examples/demo-snakemake-project/workflow/countries/Snakefile
examples/demo-snakemake-project/workflow/countries/config.yaml
examples/demo-snakemake-project/workflow/countries/envs/matplotlib.yaml
examples/demo-snakemake-project/workflow/countries/envs/xsv.yaml
examples/demo-snakemake-project/workflow/countries/scripts/plot-hist.py
examples/demo-snakemake-project/workflow/hello/MANIFEST.json
examples/demo-snakemake-project/workflow/hello/Snakefile

This reverts commit 2cf7b2ed2666f6640f19c7c6c935028b2c56e3d5.
* Readds snakemake examples that were removed for release
**Checklist**
----

refactor: Revert "remove snakemake from examples folder (#333)"

---

packages/cli/cmd/application/main.go
packages/cli/internal/pkg/aws/cdk/progress.go
packages/cli/internal/pkg/cli/context/manager.go
packages/cli/internal/pkg/cli/context/manager_test.go
packages/cli/internal/pkg/cli/flag.go
packages/cli/internal/pkg/logging/logging.go
packages/cli/internal/pkg/mocks/aws/mock_interfaces.go
site/content/en/docs/Getting started/installation.md

Issue #, if available: https://github.com/aws/amazon-genomics-cli/issues/219
This is the same change as https://github.com/aws/amazon-genomics-cli/pull/274/commits, but that was reverted because it was conflicting with the logs start flag: https://github.com/aws/amazon-genomics-cli/blob/main/packages/cli/internal/pkg/cli/logs_core.go#L18
The only difference is to remove the shorthand `-s` flag for silent.
Same sanity checks as previous PR
**Checklist**
----
*By submitting this pull request, I confirm that my …

feat: add a global --silent flag (#219)

---

scripts/cli/install.sh

* Run `npm prune --production` after building the CDK bundle
* This removes the dev dependencies, most notably the typescript compiler, from the bundle provided to the user
* This makes the bundle significantly smaller
I built a docker image, pruned the dependencies using `npm prune`, and then ran `agc account activate`. This succeeded without any import errors that might be caused by missing dependencies. It later failed due to missing credentials but I suspect that's unrelated to the CDK installation.
**Checklist**
----
*By submitting this pull request, I confirm that my contribution is …

feat: Prune out dev dependencies from the final CDK bundle

---

packages/cli/internal/pkg/cli/workflow/manager.go
packages/cli/internal/pkg/cli/workflow/workflow_run_test.go

Issue #, if available: N/A
This PR changes errors stemming from an inability to upload things to S3 to include the bucket name.
I had an issue where my S3 buckets created by AGC were being deleted by our cost-control bots due to not having the right tags.
I had to make this change to diagnose the issue, because currently AGC makes no mention of what it was attempting to upload, so it's impossible to investigate why the upload might have failed.
I used these changes to debug my failing upload and find the bucket that …

feat: Explain a bit more about S3 errors

---

README.md

Updating instructions from the run-dev.sh section to match the current behavior of the script.
N/A
**Checklist**
----

docs: Updating run-dev.sh instructions on when variables are needed.

---

scripts/cli/install.sh

Pruning dev dependencies removed modules we needed to run cdk
agc account activate was failing before. Ran agc account activate to verify cdk is not throwing errors.
**Checklist**
----

fix: remove npm prune production

---

packages/cli/internal/pkg/aws/ddb/write_workflow_instance.go
packages/cli/internal/pkg/cli/describe_output_test.go
packages/cli/internal/pkg/cli/types/workflow.go
packages/cli/internal/pkg/cli/workflow/manager.go
packages/cli/internal/pkg/cli/workflow/workflow_details.go
packages/cli/internal/pkg/cli/workflow/workflow_status.go
packages/cli/internal/pkg/cli/workflow/workflow_status_test.go
packages/cli/internal/pkg/cli/workflow_status.go
packages/cli/internal/pkg/cli/workflow_status_test.go
packages/cli/internal/pkg/wes/option/workflow_engine_params.go

Issue #, if available: N/A
This change updates the output of 'agc workflow status' to show the command run. This will show any overrides that were used and any options.
Updated unit tests to include "Request" field. This checks the status of an instance.
Ran manual testing with 'agc workflow status' to check output.
**Checklist**
----

feat: Record command run and show in agc workflow status

---

.github/workflows/github-pages.yaml

We are now referencing the releases as part of the tag. This is to validate that is the reason as to why it failed.
```
Job defined at: aws/amazon-genomics-cli/.github/workflows/github-pages.yaml@refs/tags/v1.3.0
vs
Job defined at: elliot-smith/amazon-genomics-cli/.github/workflows/github-pages.yaml@refs/heads/release
```
**Checklist**
----

chore: Validation test for why the github changes failed

---

.github/workflows/github-pages.yaml

Removes the code stopping deployment to pages
**Checklist**
----

chore: Removes if statement for deploying to pages

---

.github/workflows/github-pages.yaml

Reverting code to a previous state.
**Checklist**
----

chore: Re-adds the if check for deploying to pages

---

.github/workflows/github-pages.yml
site/content/en/docs/Workflow engines/Filesystems/_index.md
site/content/en/docs/Workflow engines/Filesystems/efs.md
site/content/en/docs/Workflow engines/Filesystems/s3.md

#363 
Added details about workflow filesystems
* `make start-docs`
* navigate to http://localhost:1313/amazon-genomics-cli/docs/workflow-engines/filesystems/
**Checklist**
----

docs: added details about workflow filesystems

---

packages/cdk/lib/constants.ts
packages/cdk/lib/constructs/batch.ts
packages/cdk/lib/types/tagged-resource-types.ts

[//]: #  This adds resource tags to root EBS volume attached to EC2 instance
[//]: #  After running a workflow go to EC2 instances and check what tags exist for attached root EBS volume
**Checklist**
----

feat: Add tags for root EBS volume

---

packages/cdk/lib/stacks/core-stack.ts

Issue #, if available: #305
This change adds a VPC gateway endpoint via the CDK for DynamoDB. 
This change was validated by confirming the VPC endpoint was returning with the correct VPC Id and Service Name. 
Steps to reproduce: 
1. `account activate -v` 
2.  [from console] VPC > endpoints > confirming Service Name and VPC ID
**Checklist**
----

feat: adds VPC gateway endpoint via the CDK for ddb

---

packages/cdk/npm-shrinkwrap.json
packages/cli/internal/pkg/cli/context/info.go
packages/cli/internal/pkg/cli/context/info_test.go
packages/cli/internal/pkg/cli/logs_core.go
packages/cli/internal/pkg/cli/logs_engine.go
packages/cli/internal/pkg/cli/logs_engine_test.go
packages/cli/internal/pkg/cli/workflow/workflow_engine.go
packages/cli/internal/pkg/cli/workflow/workflow_engine_test.go
packages/cli/internal/pkg/constants/engines.go
packages/wes_adapter/amazon_genomics/wes/adapters/NextflowWESAdapter.py

Workflows that run in engines that run as "head" processes produce distinct log streams in their log group for each run. To be useful, the `agc logs engine` command needs to be able to specify the ID of the run of interest.
A flag `-r` or `--run-id` has been added.
* If this flag is NOT set the user is warned that it should be set and that not including it will be required in the future, all streams from the log group will be displayed. This is to maintain backward compatibility.
* If the flag is set with Cromwell then an error is emitted indicating this flag is currently not supported for cromwell (adding support, if even possible, is a future task).
1. Log stream name is not known to WES API but run-id is valid. Workflow engine is not …

feat: Engine logs for specific workflow runs

---

packages/cdk/npm-shrinkwrap.json
packages/cli/internal/pkg/cli/workflow/manager.go
packages/cli/internal/pkg/wes/option/workflow_engine_params.go
packages/wes_adapter/amazon_genomics/wes/adapters/SnakemakeWESAdapter.py

This PR adding the snakemake engine to be ignored and updates the snakemakes workflow_engine_parameters from being treated as a map instead of as a list 
These changes were validated by running and deploying snakemake successfully.
**Checklist**
----

fix: updates workflow engine parameters for key, val pairing

---

site/README.md

Issue #, if available: #416
The documentation for how the CLI reference docs get generated was incorrect, and was at the end of the docs README after the steps that would require it. This provides the correct invocation to generate the reference docs and rearranges the file to make it clearer that you actually need to do it if you aren't running the Makefile.
This is what I ran to make the docs build.
**Checklist**
- N/A I have added unit tests that prove my fix is effective or that my feature works
- N/A I have linted …

docs: Update CLI reference generation instructions

---

packages/cli/internal/pkg/environment/environment.go

As @markjschreiber noted, I was using the wrong variable to provide the default Docker tag to use for the Toil server when making a Toil context. This never comes up in testing because the official Amazon releases of the containers to use here don't exist yet, and so the defaults always need to be overridden.
I'm fixing the variable reference here.
I'm also setting the default to a tag value that matches the version that Toil reports for itself when installed according to the Dockerfile for the Toil engine. When we change the Toil version we probably also want to change this tag value.
[//]: #  (A …

fix: Use Toil default tag

---

site/content/en/docs/Best practices/controllingcosts.md

I just fixed a couple of typos in the "Controlling Costs" page.
NA
**Checklist**
----

docs: Fixed 2 typos

---

packages/cli/internal/pkg/cli/account_activate.go
packages/cli/internal/pkg/cli/account_activate_test.go
site/content/en/docs/Concepts/accounts.md

fix: re-activation of an activated account deleted VPC

---

buildspec.yml

fix: enforce GO111MODULE=on for the build

---

packages/cdk/lib/constants.ts
packages/cdk/lib/stacks/context-stack.ts

uses a constant for the toil engine to be consistent with other engines
**Checklist**
----

refactor: use engine constant for toil

---

packages/cli/internal/pkg/environment/environment.go
packages/engines/toil/Dockerfile
packages/engines/toil/buildspec.yml

Update toil to `d831f74e918c4a01e961e3b45504a92d1827b8b3` commit to incorporate fixes for S3 directories etc.
* deploy context
* run all example CWL workflows to completion
* obtain logs and outputs for all worfklows
* start new workflows
* stop workflows
* confirm workflows stop
* confirm able to run example CWL workflows to completion
* destroy context
**Checklist**
----

fix: Update to Toil d831f74e918c4a01e961e3b45504a92d1827b8b3

---

README.md

Update information about using engine images when developing
**Checklist**
----

docs: Updated information about env vars used to set images

---

packages/engines/nextflow/buildspec.yml

#387 
Bump Nextflow to the latest version as of the time of this writing (22.04.1)
**Checklist**
----

fix: bump nextflow version to 22.04.1

---

site/content/en/docs/Workflow engines/cromwell.md

[//]: #  Correcting a typo
**Checklist**
----

docs: Correcting a typo in cromwell.md

---

site/content/en/docs/Getting started/helloworld.md

[//]: # Updated the hello world docs with the actual location agc installed to
**Checklist**
----

docs: Update hello world docs

---

packages/cdk/npm-shrinkwrap.json
packages/cdk/package.json

Updated CDK versions to remove dependabot warnings
1. `make init`
2. `make`
3. `make dist`
4. install AGC
5. `agc account activate`
6. for each `demo-*` project deploy all contexts defined
7. run one workflow (e.g. words with vowels)
8. check workflow succeeds
9. for each project, destroy all deployed contexts  
**Checklist**
----

chore: updated CDK package versions

---

package-lock.json
packages/cdk/npm-shrinkwrap.json
packages/cdk/package.json

build: Update CDK version to pickup latest vm2 release
Issue #, if available: https://github.com/aws/amazon-genomics-cli/security/dependabot/10
npm install successful.
**Checklist**
- [N/A] If this change would make any existing documentation invalid, I have included those updates within this PR
- [Y] Title of this Pull Request follows Conventional Commits standard: https://www.conventionalcommits.org/en/v1.0.0/
----
*By submitting this pull request, I confirm that my contribution is …

Update CDK to pickup latest vm2

---

.devcontainer/devcontainer.json

Add devcontainer for use in developing on vscode.
**Checklist**
----

chore: Add vscode devcontainer

---

packages/cdk/lib/stacks/core-stack.ts
site/content/en/docs/Concepts/accounts/index.md

Issue #, if available: https://github.com/aws/amazon-genomics-cli/issues/533
Add EC2 endpoint. Update docs.
**Checklist**
----

chore: Add EC2 Service Endpoint to AGC created VPCs

---

packages/engines/cromwell/buildspec.yml

Updated cromwell version to Loka(83.1-AWS)

---

packages/cdk/npm-shrinkwrap.json
scripts/cli/install.sh

Issue #, if available: Found in conversation of #569
Fixes problem noticed post merge [here](https://github.com/aws/amazon-genomics-cli/pull/569#discussion_r1036393642)
`make init && make release && ./dist/amazon-genomics-cli/install.sh`
**Checklist**
----

fix: Install script output name

---

examples/demo-snakemake-project/workflow/countries/Snakefile

Issue #, if available: https://github.com/aws/amazon-genomics-cli/issues/498
The demo no longer works when running with snakemake v7.18.2, citing a `matplotlib` import error. This PR fixes the issue.
See [here](https://amzn-aws.slack.com/archives/C049K2W7GJC/p1670360460741929).
Run the `countries` demo on a snakemake context deployed to use snakemake v7.18.2 docker image. The workflow should run without any errors. 
**Checklist**
----
*By submitting this pull request, I confirm that my contribution is made under the …

chore: Update snakemake demo to work with snakemake v7.18.2

---

packages/cli/.agcignore
packages/cli/internal/pkg/osutils/utils.go

codon172 adding .agcingore file

---

packages/cdk/lib/env/context-app-parameters.ts

Issue #, if available: 545
**Checklist**
----

feat: Cross Account KMS

---

packages/cdk/lib/env/context-app-parameters.ts

Previous SSE-KMS policy code in the CDK adaptor throws an error if the KMS key is empty, even when it's not needed. This fix uses a method that catches the throw and allows a default null value.
Ran all tests on an AL2 instance.
**Checklist**
----

fix: Allow null kms decrypt policy

---

packages/cdk/lib/env/context-app-parameters.ts
packages/cdk/npm-shrinkwrap.json

Previous SSE-KMS policy code in the CDK adaptor throws an error if the KMS key is empty, even when it's not needed. This fix uses a method that catches the throw and allows a default undefined value.
**Checklist**
----

fix: Default to undefined

---

.github/workflows/github-pages.yml

Bump go version to match main project

fix: Update go version

---

site/content/en/docs/Workflow engines/Filesystems/efs/index.md

#590 
Updated information about EFS provisioned throughput to include units and information about additional costs. 
`make start-docs`
Navigate to page on localhost and inspect rendered content.
**Checklist**
----

docs: Update information about EFS throughput (issue-590)

---

extras/agc-minimal-permissions/package-lock.json
extras/agc-minimal-permissions/package.json
packages/cdk/npm-shrinkwrap.json
scripts/package-lock.json
scripts/package.json

[//]: #  Removes vm2 dependency and updates other dependencies to remove deprecation warnings.
[//]: #  Successfully ran demo
**Checklist**
- [x ] If this change would make any existing documentation invalid, I have included those updates within this PR
- [x ] I have added unit tests that prove my fix is effective or that my feature works
- [x ] I have linted my code before raising the PR
- [ x] Title of this Pull Request follows Conventional Commits standard: https://www.conventionalcommits.org/en/v1.0.0/
----

build: Updated deprecated dependencies

---

.github/workflows/github-pages.yml

Updates docs build from branch
Updates docs generation branch so we can post EOL notice.
----

chore: Update github-pages.yml

---

site/content/en/docs/Concepts/_index.md

chore: fixes typo

---

site/content/en/docs/Concepts/_index.md
site/content/en/docs/Contribution guidelines/_index.md
site/content/en/docs/Examples/_index.md
site/content/en/docs/Getting started/_index.md
site/content/en/docs/Overview/_index.md
site/content/en/docs/Reference/_index.md
site/content/en/docs/Tutorials/_index.md
site/content/en/docs/Workflow engines/Filesystems/_index.md
site/content/en/docs/Workflow engines/_index.md

chore: fix typo in docs
