site/content/en/docs/Getting started/installation.md
`s3://healthai-public-assets-us-east-1/amazon-genomics-cli/0.9.0/amazon-genomics-cli.zip` is not public accessible. It must be updated to `1.0.0`.
On the other hands, I think using `latest` instead of version number could be better for tutorial document.
=> update version number in the S3 path

site/content/en/docs/Getting started/helloworld.md
`--context` option is required for `agc context deploy`.
=> fix typo in Getting Started docs

packages/cli/internal/pkg/cli/context/manager.go, packages/cli/internal/pkg/cli/context/manager_info_test.go, packages/cli/internal/pkg/cli/spec/project.go, packages/cli/internal/pkg/cli/spec/project_test.go, packages/cli/internal/pkg/cli/workflow/manager.go
Currently, we retrieve the context information in several locations using different error messages. This change allows us to centralize the error messaging between the different components.
=> Centralizes the logic for retrieving context information

.github/workflows/ci.yml
*Description of changes:* After refactoring out the common package, `/packages/cli` is now the base directory for the go project. Update the CI workflow to reflect that.
=> Target new base Go dir after refactor

packages/cli/internal/pkg/cli/project_init.go
Updates the Use part of the project init command. I also checked the documentation but we include workflow type there which is why it isn't updated there.
=> Adds workflow type to the command use example for project init

packages/cdk/lib/stacks/nested/batch-stack.ts
Use nested stack parent tags as `resourceTags` for Batch construct.
`agc context deploy -c spotCtx`
Compute Environment contains expected EC2 tags
=> Restore tags to ec2 instances used by AWS Batch

.github/workflows/notify.yml
I'm removing the title from the Slack payload. Quotes in the title can escape the workflow payload JSON, causing the Slack workflow to fail. Since Slack expands the PR link with a preview, the title is less important to have in the message.
=> Remove title from slack payload

packages/cli/internal/pkg/cli/logs_core.go, packages/cli/internal/pkg/cli/logs_workflow_test.go
[println](https://pkg.go.dev/builtin#println) is a builtin function in Go. We were overriding that function which could have unintended consequences. I am renaming our function to `printLn` to avoid the conflict.
Additionally, I have replaced lint exception comments with Blank Identifiers to explicitly indicate we don't care about the return values rather than rely on the linter comment.
=> Rename println to avoid builtin name clash

README.md
Remove hardcoded Node version so it can intelligently pick the correct version of Node from `.nvmrc`
=> Remove hardcoded Node version

packages/cli/internal/pkg/cli/context_status.go
The `context status` command prints nothing if no contexts are deployed. I am modifying the command to inform the user when this is the case.
No contexts
```
$ agc context status
2021-10-04T12:50:09-07:00 𝒊  There are no contexts deployed.
```
One context
```
$ agc context status
INSTANCE	myContext		STARTED	true
```
=> Display message if no contexts deployed

site/content/en/docs/Getting started/helloworld.md
`agc workflow status` command was missing the `-r` flag to indicate that the string we are passing in is the run-id.
[//]: #  This change makes the workflow status command in the tutorial work.
[//]: # Ran the command successfully as well as referred to agc workflow status --help documentation which declares the -r (or --run-id) flag is necessary when specifying the run-id string.
**Checklist**
----
=> Add run-id flag to workflow status command

site/content/en/docs/Getting started/installation.md
Updates the installation instructions to download the latest release. See https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases
Ran:
```bash
curl -OLs https://github.com/aws/amazon-genomics-cli/releases/latest/download/amazon-genomics-cli.zip
```
validated it works ✅
----
=> Latest Release Link

packages/cli/cmd/application/description.go, packages/cli/internal/pkg/cli/group/group.go, packages/cli/internal/pkg/logging/prefix.go
Release builds failed due to malformed go tags, this reverts the change to the correct tags.
`make release`
**Checklist**
----
=> fix: use proper go tags for windows build

site/content/en/_index.html
correctly point AWS health link to `aws.amazon.com/health`
**Checklist**
- [ x] If this change would make any existing documentation invalid, I have included those updates within this PR
- [ x] I have added unit tests that prove my fix is effective or that my feature works
- [ x] I have linted my code before raising the PR
- [ x] Title of this Pull Request follows Conventional Commits standard: https://www.conventionalcommits.org/en/v1.0.0/
----
*By submitting this pull request, I confirm that my …
=> fix: invalid AWS Health url

packages/cli/internal/pkg/aws/cwl/stream_logs.go, packages/cli/internal/pkg/aws/cwl/stream_logs_test.go, packages/cli/internal/pkg/cli/logs_core.go, packages/cli/internal/pkg/cli/logs_core_test.go, packages/cli/internal/pkg/mocks/io/interfaces.go, packages/cli/internal/pkg/mocks/io/mock_interfaces.go
Issue #, if available: NA
Description of Changes
Currently, when you run the tail logs command it can look like the command hung when it is run. This change provides some messaging to the user so that they are aware that the reason that there are no logs shows is because there aren't any new ones. This also adds back the logic to send through empty logs when no new events are sent back from Cloudwatch
NB: The current approach can show the message immediately before messages are shown if they exist since we split up the request to AWS if the number of streams is larger than the limit (greater than 100 streams). However this is unlikely and could also happen if the logs start appearing immediately after the first request is made to AWS. Since this could occur naturally anyway, would make …
=> fix: Adds a message when new logs aren't shown to the user immediately

packages/cli/internal/pkg/aws/cdk/deploy_app.go, packages/cli/internal/pkg/aws/cdk/execute_cdk.go, packages/cli/internal/pkg/aws/cdk/execute_cdk_test.go, packages/cli/internal/pkg/cli/config/config_client.go
1. In case when cdk command cannot be executed the temporary directory is not cleaned up
1. Unit tests for cdk command execution don't check returned error, expected call to mocked methods, etc
1. Unit tests contain a lot of duplicated boilerplate code that clutter the test logic
1. build
1. unit tests
1. manual test
**Checklist**
----
=> fix: temporary folder potential leak in some error scenarios. unit test for cdk command execution

packages/cli/internal/pkg/cli/context_describe.go, packages/cli/internal/pkg/cli/context_describe_test.go, site/content/en/docs/Tutorials/walkthrough.md
Issue #, if available: NA
Currently, the command `agc context describe` does not allow a context to be passed in as an argument via `-c` while context destroy/deploy which breaks the consistency for that high level command. Our documentation also refers to requiring `-c` which currently isn't supported. This change updates the documentation to remove the `-c` command and allows the command to accept the context via the `-c` argument.
```
$ agc context describe spotCtx -c myContext
Error: either the '-c' flag or a contexts must be provided, but not both
$ agc context describe
Error: a context must be provided
$ agc context describe spotCtx
2021-11-04T12:06:27-07:00 𝒊  Describing context 'spotCtx'
CONTEXT	256	spotCtx …
```
=> fix: updates context describe to be consistent with context destroy

examples/gatk-best-practices-project/gatk4-basic-joint-genotyping/gatk4-basic-joint-genotyping.wdl
Best practice is to avoid mutation of inputs to a workflow. Further miniwdl prevents it. Therefore use copy instead of moving the input file.
`agc workflow run basic-joint-genotyping -c spotCtx
**Checklist**
- [*] Title of this Pull Request follows Conventional Commits standard: https://www.conventionalcommits.org/en/v1.0.0/
----
=> fix: copy instead of move input

scripts/package-release.sh
fixes: #136
Moving the release files one folder down to avoid bombing cwd.
Ran in forked build pipeline, confirmed it works.
**Checklist**
----
=> build: Move release files one folder down

packages/cli/internal/pkg/aws/cwl/get_logs.go, packages/cli/internal/pkg/aws/cwl/get_logs_test.go, packages/cli/internal/pkg/aws/cwl/stream_logs.go, packages/cli/internal/pkg/aws/cwl/stream_logs_test.go
Issue #, if available: NA
Currently, logs are shown directly as configured from Cloudwatch. This can end up causing logs to be interleaved with one another which can be confusing. This PR forces the logs to be grouped together by the log group.
API Source: https://github.com/aws/aws-sdk-go-v2/blob/service/cloudwatchlogs/v1.8.0/service/cloudwatchlogs/api_op_FilterLogEvents.go#L68
Example
```
[Wed, 27 Oct 2021 14:54:30 -0700	nxf-scratch-dir ip-10-0-135-228.us-west-2.compute.internal:/tmp/nxf.tI8K4PhVO2]
[Wed, 27 Oct 2021 14:54:32 -0700	.command.sh: line 2: unexpected EOF while looking for matching `'']
[Wed, 27 Oct 2021 14:54:58 -0700	nxf-scratch-dir ip-10-0-135-228.us-west-2.compute.internal:/tmp/nxf.qRSZYD5f7u]
[Wed, 27 Oct 2021 14:54:58 -0700	nxf-scratch-dir …
```
=> fix: updates how the logs are shown from cloudwatch

site/content/en/_index.html
fixes: #135
The contrast on the home page of the docs in one section was well below accessibility standards. This looks to be largely an issue with how Docsy determines how to color the font in the default theme. In order to avoid any additional side effects by overriding the theme variables, I'm opting to just change the color of the section. Docsy is at least smart enough to select dark color text when the background is white.
Ran `hugo server -D` locally and confirmed contrast ratios are > 4.5*
*The link is only 2.64 normally, but 7.49 when hovered.
**Checklist**
----
=> docs: improve contrast in docs

packages/cli/internal/pkg/aws/cwl/get_logs_test.go
The current test for "TestClient_GetLogs" is not deterministic. This change fixes that
Changed the check of the array to be a contains (deterministic) and validated the split of the logs by location by checking the first element in each section to be the "hello" keyword.
if others know if we can validate them better (I wasn't a fan of an else for checking the order) or has a different preference, I can update them to use that style instead.
**Checklist**
----
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 …
=> fix: Asserts order deterministically

packages/cli/internal/pkg/aws/cfn/stack_filters.go, packages/cli/internal/pkg/cli/workflow/manager.go, packages/cli/internal/pkg/cli/workflow/workflow_status_test.go
Issue #, if available: NA
Whenever a customer runs `agc workflow status` while a stack is actively being destroyed or has been destroyed, AGC will still try to query WES to determine the status of workflows that have been ran. This change removes stacks that are currently being removed so that it follows the same logic as stacks that have been removed since we can't trust the status of those stacks.
1. Deployed two contexts
2. Ran two workflows on each of the contexts
3. Waited for the workflows to finish
4. Destroyed one of the contexts and while it was being destroyed, ran `agc workflow status`
```
$ agc workflow status
2021-11-02T09:24:16-07:00 𝒊  Showing workflow run(s). Max Runs: 20
WORKFLOWINSTANCE	spotContext …
```
=> fix: Workflow status now ignores unqueryable stacks

.github/workflows/ci.yml, packages/cli/internal/pkg/cli/format/format.go, packages/cli/internal/pkg/cli/logs_workflow.go, packages/cli/internal/pkg/cli/logs_workflow_test.go, packages/cli/internal/pkg/cli/workflow/workflow_status.go, packages/cli/internal/pkg/cli/workflow/workflow_tasks.go, packages/cli/internal/pkg/mocks/manager/mock_interfaces.go
By default, workflow logs for a run will log out run status and individual task status.
Tasks logs can be emitted with `--task <taskId>` for a single task log, `--all-tasks` for all task logs, and `--failed-tasks` for failed task logs.
Verified commands manually 
```
$ agc logs workflow foo
2021-11-09T17:17:01-08:00 𝒊  Showing the logs for 'foo'
2021-11-09T17:17:02-08:00 𝒊  Showing logs for the latest run of the workflow. Run id: '4927d57c-5181-4505-9e9f-96a7590ea9eb'
RunId: 4927d57c-5181-4505-9e9f-96a7590ea9eb
State: COMPLETE
Tasks: 
Name                    JobId …
```
=> feat: Improved Workflow logs

packages/cli/internal/pkg/aws/cdk/execute_cdk.go, packages/cli/internal/pkg/aws/cdk/execute_cdk_test.go
The progress bar update was broken because of incorrect regex expression
- make
- unit tests
- manual test
**Checklist**
----
=> fix: progress bar doesn't show any progress

packages/cli/internal/pkg/aws/cwl/stream_logs_test.go
Events are accumulated in a map with key being log stream name. Order of keys in map is not guaranteed by the implementation. In unit test we cannot require particular order, or it will cause sporadic unit test failures. 
- make
- unit test is back to stable
**Checklist**
----
=> fix: use proper assertion in order to avoid sporadic unit test failures

packages/cdk/lib/constructs/engines/engine.ts, packages/cdk/lib/constructs/engines/miniwdl/miniwdl-engine.ts, packages/cdk/lib/constructs/engines/nextflow/nextflow-engine.ts, packages/cdk/lib/stacks/nested/miniwdl-engine-stack.ts, packages/cdk/lib/stacks/nested/nextflow-engine-stack.ts, packages/cdk/lib/wes_adapter/amazon_genomics/tests/test_MiniwdlWESAdapter.py, packages/cdk/lib/wes_adapter/amazon_genomics/wes/adapters/MiniWdlWESAdapter.py, packages/cdk/lib/wes_adapter/requirements.txt, packages/cdk/lib/wes_adapter/rest_api/controllers/workflow_execution_service_controller.py
Issue #, if available: https://github.com/aws/amazon-genomics-cli/issues/169, https://github.com/aws/amazon-genomics-cli/issues/170
Previously the MiniWDL S3 output location was set to a custom S3
path in the AGC Output bucket. This does not follow the same
convention as the other two engines. This commit replaces that
custom path with the standard project/user/context prefix.
Also implements fetching from this path within the WES adapter so `workflow output` works.
ran workflow, validated that outputs are the same between cromwell and miniwdl
$ agc workflow status
2021-11-12T23:07:43Z 𝒊  Showing workflow run(s). Max Runs: 20
WORKFLOWINSTANCE	miniContext	559ba5b9-f4a7-4069-8a3a-f2965521015d	true	COMPLETE …
=>  fix: Correcting MiniWDL output location 

packages/cdk/lib/wes_adapter/amazon_genomics/tests/test_BatchAdapter.py, packages/cdk/lib/wes_adapter/amazon_genomics/wes/adapters/BatchAdapter.py
Currently the CLI and WES adapter are using different ISO time formats.
The CLI expects a timezone, and the Batch WES adapter is not returning one.
This commit adds timezone information to the returned timestamps so the CLI
can parse them.
Workflow logs command now parses the timestamps appropriately.
Old
```
$ agc logs workflow hello-3 -r 140ce218-aa39-478f-8b4e-0696dbf386a1 -v
2021-11-12T23:53:30Z ↓  Checking AGC version...
2021-11-12T23:53:30Z 𝒊  Showing the logs for 'hello-3'
2021-11-12T23:53:30Z ↓  Showing logs for workflow run '140ce218-aa39-478f-8b4e-0696dbf386a1'
2021-11-12T23:53:30Z ↓  GetRunLog '140ce218-aa39-478f-8b4e-0696dbf386a1'
2021-11-12T23:53:30Z ↓ …
```
=> fix: Return timezone information in RunLog

packages/cli/internal/pkg/cli/spec/io_test.go, packages/cli/internal/pkg/cli/spec/project_schema.json
Prevent extra keys or misspelled keys in project yaml files.
* `make`
* In each example project directory `agc project validate`
**Checklist**
----
=> fix: prevent extra keys in agc-project.yaml

README.md
Brew prefix may not necessarily be set to `/usr/local/`
Move from MacOS suggestion of prepending `"/usr/local/opt/gnu-sed/libexec/gnubin"` to `PATH` env var to instead - `"$(brew --prefix gnu-sed)/libexec/gnubin"`
```
ls "$(brew --prefix gnu-sed)/libexec/gnubin"
sed
```
**Checklist**
----
=> docs: Use brew --prefix over /usr/local

packages/cdk/lib/util/index.ts
We're currently seeing timeouts in our integration tests when calling
the Cromwell WES adapter. It seems like cold start and initializing the
connection to Cromwell on the first invocation can take longer than 30 seconds
**Checklist**
----
=> fix: Increasing WES adapter lambda timeout

CHANGELOG.md, packages/cdk/lib/util/index.ts
We're currently seeing timeouts in our integration tests when calling
the Cromwell WES adapter. It seems like cold start and initializing the
connection to Cromwell on the first invocation can take longer than 30 seconds
**Checklist**
----
=> fix: Increasing WES adapter lambda timeout (#180)

packages/cdk/lib/stacks/core-stack.ts, packages/cdk/lib/stacks/engines/cromwell-engine-construct.ts, packages/cdk/lib/stacks/engines/engine-construct.ts, packages/cdk/lib/stacks/engines/miniwdl-engine-construct.ts, packages/cdk/lib/stacks/engines/nextflow-engine-construct.ts, packages/cdk/lib/util/index.ts
fix: fixing monocdk imports
[//]: #  one of the recent monocdk npm packages have restructured the file tree inside the package, changing the import calls from our code to be agnostic of that change.
[//]: #  Ran `npm run build` to verify the new import calls are working fine
**Checklist**
----
=> fix: fixing monocdk imports

.github/workflows/github-pages.yaml
This needs to be merged into the release branch. At the moment, if we build from release, it's looking for main and if we build from main, it's looking for release, so no docs can be generated.
Since this is a docs-only change, I don't plan on making a new release.
=> docs: Publish on release branch

packages/cli/internal/pkg/cli/configure_format.go, packages/cli/internal/pkg/cli/configure_format_test.go
Argument checks for `agc configure format` was not handled gracefully. This caused stack error to output into the console.
```
$ agc configure format
panic: runtime error: index out of range [0] with length 0
```
```
$ agc configure format
Error: format value must be provided
```
**Checklist**
----
=> fix: fixed arg validation for format

packages/cdk/lib/stacks/engines/miniwdl-engine-construct.ts
We currently don't set the maxVCpus from the contextParameters when
creating MiniWDL Batch resources. This commit ensures that we do.
This is possible because the code instantiating these resources is
duplicated. A refactor to remove this duplication will be done in a
subsequent commit, so as not to pollute the patch release.
fixes #184 
Deployed context with maxVcpu set, the value is now respected.
**Checklist**
----
=> fix: Respect maxVCpus in miniwdl contexts

packages/cli/internal/pkg/cli/config/config_client.go, packages/cli/internal/pkg/cli/config/config_client_test.go, packages/cli/internal/pkg/cli/config/config_test.go, packages/cli/internal/pkg/cli/config/io.go
This is a follow up to address the comments in https://github.com/aws/amazon-genomics-cli/pull/197. This change involves adding a function that returns the default config.
``` 
$ agc configure email test@email.com
2021-12-01T09:29:09-08:00 𝒊  Setting user email address to: 'test@email.com'
$ agc configure describe
2021-12-01T09:29:12-08:00 𝒊  Reading user specific configuration
CONFIG
FORMAT  text
USER    test@email.com  test1X6OLM
$ agc 
```
**Checklist**
----
*By submitting this pull request, I …
=> fix: function for default config

packages/engines/nextflow/Dockerfile
Using a fixed version of java, since the latest one by default is now 17 which doesn't work for us here. I'm fixing it to the last known version that has worked
Iv'e rebuilt the image both locally and on the pipeline in my aws account, all worked.
**Checklist**
----
=> fix: Using fixed java version for nextflow

site/config.toml, site/content/en/docs/Concepts/engines.md, site/content/en/docs/Concepts/workflows.md
Cherry pick of doc update from main
* Improved documentation of MANIFEST, directories and engines.
* Use root URL recommended in Hugo documentation (https://gohugo.io/hosting-and-deployment/hosting-on-github/)
* updated go.mod
(cherry picked from commit a0a43dbbb9834497f283b9833a1b0e55ab3ee69a)
----
=> docs: improve manifest and source url docs (#214)

packages/cli/internal/pkg/cli/workflow/manager.go, packages/cli/internal/pkg/cli/workflow/workflow_run.go, packages/cli/internal/pkg/cli/workflow/workflow_run_test.go
We currently search for the agc-project.yaml file and chdir into the
project directory in case AGC is run from a folder below the top-level
project folder. This means that when looking for files in the args command,
the CLI is not looking in the users current directory, meaning they must
specify --args files relative to the project.yaml rather than their
working directory. This commit changes AGC to prepend the project directory
to any workflow lookups, so the working directory remains the same as the users.
fixes #83 
Able to run `read` and `words-with-vowels` workflows
* from within `demo-wdl-project/workflows/read`: `agc workflow run read --args read.inputs.json -c miniContext`
* from within `demo-wdl-project`: `agc workflow run read --args …
=> fix: Remove Chdir when looking for project files

packages/cdk/lib/constants.ts
This change fixes the order of operations for the launch template script as it currently tries to execute a script that doesn't exist yet.
agc account activate && agc context deploy --all
**Checklist**
----
=> fix: Fixes execution order for the Launch Template

packages/cli/internal/pkg/cli/context_deploy.go
Issue #, if available: #187
Added context deployment completion function as valid arguments when `-c` flag is not present
Tested autocomplete without change, then reinstalled agc with the new change, re-initiated autocomplete, and tested that context completion works without flag.
**Checklist**
----
=> fix: added auto complete when -c flag is not present

packages/cdk/apps/core/app.ts, packages/cdk/lib/stacks/core-stack.ts
The construct we use to upload batch artifacts prunes the target bucket by default. I have disabled that functionality and also moved the artifacts one level deeper in the parent bucket. This will keep the root folder clean and allow us to reenable pruning if we ever need since it won't target the whole bucket.
`agc account activate` and ran hello workflows for cromwell and miniwdl contexts to verify they still run successfully.
**Checklist**
----
*By submitting this pull request, I confirm that my contribution is made …
=> fix: nest batch artifacts and disable bucket clean up

examples/nf-core-project/workflows/rnaseq/MANIFEST.json
Modify the rnaseq of nf-core to a pinned version compatible w/ our shipped version of nextflow
1. Ran example without `-r 3.4`. Failed with `EXECUTOR_ERROR`
2. Ran example with `-r 3.4`. Recieved `SUCCEEDED`. 
**Checklist**
- [Y] If this change would make any existing documentation invalid, I have included those updates within this PR
- [Y] I have added unit tests that prove my fix is effective or that my feature works
- [Y] Title of this Pull …
=> fix: Pinned running of rnaseq to version 3.4 (closes #246)

packages/cli/cmd/application/main.go, packages/cli/internal/pkg/aws/cdk/progress.go, packages/cli/internal/pkg/cli/context/manager.go, packages/cli/internal/pkg/cli/context/manager_test.go, packages/cli/internal/pkg/cli/flag.go, packages/cli/internal/pkg/logging/logging.go, packages/cli/internal/pkg/mocks/aws/mock_interfaces.go, site/content/en/docs/Getting started/installation.md
Issue #, if available: https://github.com/aws/amazon-genomics-cli/issues/219
Add a new "--silent" flag that suppresses all diagnostic information (no progress, no cdk output, no logs on success)
Test commands with and without the `--silent` flag
```
dtzeng@u787d729b615b5f:/workplace/dtzeng/amazon-genomics-cli/examples/demo-wdl-project$ ../../scripts/run-dev.sh 
Setting up CDK
Running the agc CLI
^C will interrupt the agc command
To exit this script, use ^\ or ^Z
$ agc help
🧬 Launch and manage genomics workloads on AWS.
Commands 
Getting Started 🌱
account     Commands for AWS account setup.
Install or remove AGC from your account.
Contexts
context     Commands for contexts.
Contexts specify workflow engines and …
```
=> feat: add a global --silent flag (#219)

packages/cdk/lib/wes_adapter/amazon_genomics/wes/adapters/CromwellWESAdapter.py, packages/cli/internal/pkg/cli/logs_workflow.go, packages/cli/internal/pkg/cli/logs_workflow_test.go, packages/cli/internal/pkg/cli/workflow/workflow_tasks.go, packages/cli/internal/pkg/cli/workflow/workflow_tasks_test.go, packages/wes_api/client/model_log.go
* In its current state, if the job is successfully, the returnCode for all tasks will show 0. In the metadata received from Cromwell engine, we see the returnCode for the task being 0.
* Similarly, if the job has failed, the returnCode for all tasks will still show 0. However, in the metadata received from Cromwell engine we don’t see any returnCode key.
In its current state, when the job has failed, the returnCode is not accurate and therefore not useful. As we are unable to retrieve a returnCode from Cromwell on a failed job at times, with this new change, we will instead display an empty string (instead of 0) when returnCode is not available in order to not provide misleading information to customers.
[//]: #  (A description of the …
=> fix: correctly handle missing return code from Cromwell executions

packages/cli/go.mod, packages/cli/go.sum
goimports package recently updated to 0.1.9 on Jan 25: https://pkg.go.dev/golang.org/x/tools@v0.1.9/cmd/goimports?tab=versions
Causing transitive dependency issues and failing checks in new PRs.
```
go: downloading golang.org/x/tools v0.1.8
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: downloading golang.org/x/sys v0.0.0-20211019181941-9d821ace8654
go get: installing executables with 'go get' in module mode is deprecated.
To adjust and download dependencies of the current module, use 'go get -d'.
To install using requirements of the current module, use 'go install'.
To install ignoring the current module, use 'go install' with a version,
like 'go install example.com/cmd@latest'.
For more information, see …
```
=> fix: update go dependency versions

packages/cdk/lib/wes_adapter/amazon_genomics/wes/adapters/BatchAdapter.py
Nextflow workflow logs unable to unmarshal number. This is causing nextflow workflows to not show any workflow logs. 
I deployed a workflow for miniwdl, Cromwell, Nextflow engines. 
This is running hello workflow for nextflow for onDemandContext
```
$ agc workflow run hello -c onDemandContext -v
2022-01-28T17:29:53-08:00 ↓  Checking AGC version...
2022-01-28T17:29:53-08:00 𝒊  Running workflow. Workflow name: 'hello', Arguments: '', Context: 'onDemandContext'
2022-01-28T17:29:55-08:00 ↓  No …
```
=> fix: Nextflow workflow logs unable to deserialize

packages/cdk/lib/artifacts/batch-artifacts/ecs-additions/get-amazon-ebs-autoscale.sh, packages/cdk/lib/artifacts/batch-artifacts/ecs-additions/provision.sh, packages/cdk/lib/constants.ts, packages/cdk/lib/constructs/batch.ts, packages/cdk/lib/constructs/launch-template-data.ts, packages/cdk/lib/stacks/context-stack.ts, packages/cdk/lib/stacks/engines/batch-construct.ts, packages/cdk/lib/stacks/engines/miniwdl-engine-construct.ts
#278
#275
* Make LaunchTemplate user data aware of workflow orchestrator (engine). Don't use ebs-autoscale when running miniwdl.
* Add code comment  about the need to redeploy contexts when changing the LaunchTemplate.
* Change shutdown to echo error because shutdown won't cause batch to restart a new instance.
* Exposed initial ebs volume size to provision.sh to make it easier to change this value.
* fixed additional typo/ bug from issue 275
Because the changes here modify the ecs-additions scripts a full account deactivate, activate is required.
* deploy miniwdl context and run `demo-wdl-project` workflows. Make sure the autoexpand EBS volume is *not* created on batch workers
* deploy cromwell …
=> feat: don't use ebs auto scale for minidl

packages/cdk/.npmrc, packages/cdk/Makefile, packages/cdk/package.json
Issue #, if available: [294](https://github.com/aws/amazon-genomics-cli/issues/294), [292](https://github.com/aws/amazon-genomics-cli/issues/292)
Force use version 14 when running npm
Ran `make init` which calls `npm ci` with version 15, 16, 17 and verified failure with message engine node version is not v14. Reran `make init` with version 14 succeeded.
v17 logs
```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: cdk@0.1.0
npm ERR! notsup Not …
```
=> fix: force use node v14 in cdk package

packages/cdk/lib/artifacts/batch-artifacts/ecs-additions/get-amazon-ebs-autoscale.sh, packages/cdk/lib/artifacts/batch-artifacts/ecs-additions/provision.sh, packages/cdk/lib/constructs/batch.ts, packages/cdk/lib/constructs/launch-template-data.ts, packages/cdk/npm-shrinkwrap.json
* better resilience of provisioning scripts
* better diagnostic logging from provisioning scripts
* trapped `ERR` or `INT` will cause the instance to mark itself unhealthy, preventing the the ecs-agent from restarting and joining the cluster as a worker that is not properly configured. By marking itself unhealthy the Batch clusters autoscaler will replace it rapidly.
* `make`
* `make release`
* install agc
* activate account
* deploy spotCtx and run demo-wdl-project workflows.
* confirm updated scripts are in S3 bucket
* ensure workflows succeed
* ensure detailed logs are found in `/aws/ecs/container-instance/agc` log group 
* confirm Batch ec2 workers have permission policy for `autoscaling:SetInstanceHealth` …
=> feat: improve reliability of provision scripts

packages/cli/internal/pkg/cli/context/manager.go, packages/cli/internal/pkg/cli/context/manager_deploy_test.go
Currently the cross-region replication is already in place and is correctly using the container in the region specified in the user's profile. However, the validation step for checking if the image exists is still using the default region ("us-east-1") in the environment config. This change ensures the container validation is checked against the user's region before deploying the context in that region.
`agc account activate`, `agc deploy context` and `agc run workflow` in us-west-1
``` …
```
=> fix: container validation check with the correct region from user profile

packages/cli/internal/pkg/aws/s3/delete_bucket.go, packages/cli/internal/pkg/aws/s3/delete_bucket_test.go, packages/cli/internal/pkg/aws/s3/delete_object.go, packages/cli/internal/pkg/aws/s3/delete_object_test.go, packages/cli/internal/pkg/aws/s3/empty_bucket.go, packages/cli/internal/pkg/aws/s3/empty_bucket_test.go, packages/cli/internal/pkg/aws/s3/interface.go, packages/cli/internal/pkg/cli/account_deactivate.go, packages/cli/internal/pkg/cli/account_deactivate_test.go, packages/cli/internal/pkg/cli/awsresources/awsresources.go, packages/cli/internal/pkg/mocks/aws/mock_interfaces.go
When deactivating an AGC-CDK bootstrapped account, we do not delete the assets bucket associated with the bootstrap stack, causing subsequent activations to fail.
Activated and deactivated and reactivated account to confirm bucket is deleted and does not block reactivation.
**Checklist**
----
=> fix: Delete bootstrap bucket on account deactivate

packages/cdk/lib/artifacts/batch-artifacts/ecs-additions/provision.sh
Corrected if statement that was preventing use of EBS auto expansion in all engines
Validated syntax in a Bash terminal:
```
export WORKFLOW_ORCHESTRATOR=cromwell
$ if [ "$WORKFLOW_ORCHESTRATOR" != "miniwdl" ] && [ "$WORKFLOW_ORCHESTRATOR" != "snakemake" ]; then
> echo "not miniwdl or snakemake"
> fi
not miniwdl or snakemake
```
**Checklist**
----
=> fix: hot fix for bug with if statement in provision script

packages/cdk/lib/artifacts/batch-artifacts/ecs-additions/provision.sh
Our provision script has an unassigned variable. Not a major issue as it only impacts a logging statement and would only become an issue if we allow people to provide custom AMIs which may have different OSs
**Checklist**
----
=> fix: minor fix for unassigned variable

packages/cli/internal/pkg/cli/workflow/manager.go, packages/cli/internal/pkg/cli/workflow/workflow_run.go, packages/cli/internal/pkg/cli/workflow/workflow_run_test.go, packages/cli/internal/pkg/mocks/io/interfaces.go, packages/cli/internal/pkg/mocks/io/mock_interfaces.go
Currently single definition workflows fail to initialize due to incorrect logic around zipping the contents. This has been changed to take this into consideration when running the workflows
Ran multiple single and multi file definition workflows in AGC.
```
$ agc workflow run read -c miniContext
2022-02-16T08:45:31-08:00 𝒊  Running workflow. Workflow name: 'read', Arguments: '', Context: 'miniContext'
f352bfe2-77bb-41c2-920d-c2121a92d4cc
$ agc workflow run hello -c miniContext
2022-02-16T08:45:55-08:00 𝒊  Running workflow. Workflow name: 'hello', Arguments: '', Context: 'miniContext'
3b1443d1-940e-485d-a3b5-b0cdd8921650
$ agc
```
**Checklist**
----
*By submitting this pull request, I confirm …
=> fix: Fixes issues with workflows that only have a single file

packages/wes_adapter/index.py
#322 
This bug is due to the WES adapter, when the header isn't standard (normally application/error+json) the output returned is a base64 string. This fix converts the base64 string to Json. 
This change was tested locally - running agc with updated index.py allows for seamless use. Tested by removing main.wdl which causes 500.
**Checklist**
----
=> fix: corrects wes return value from base64 to json

.github/workflows/github-pages.yaml
Removed redundant `npm install` commands from github-pages workflow to correct npm package conflicts. The required npm install happens in `make docs` which now also pins the desired hash of docsy.
triggered github-pages action in my fork of this repo and observed that it ran to completion
**Checklist**
----
=> fix: Update github-pages.yaml

packages/cli/internal/pkg/cli/configure_format.go, packages/cli/internal/pkg/cli/configure_format_test.go, packages/cli/internal/pkg/cli/flag.go, packages/cli/internal/pkg/cli/format/common_types.go, packages/cli/internal/pkg/cli/format/format.go, packages/cli/internal/pkg/cli/format/json.go, packages/cli/internal/pkg/cli/format/json_test.go, site/content/en/docs/Getting started/installation.md
Issue #, if available: https://github.com/aws/amazon-genomics-cli/issues/215
- Fix the `agc configure format` command as that was never working as-is.
- Added a new json format class that extends the formatting interface
- Added unit tests/reshuffled some shared types
Added unit tests
Testing `agc configure format` manually
```
dtzeng@u787d729b615b5f:/workplace/dtzeng/amazon-genomics-cli/examples/demo-wdl-project$ agc configure format text
2022-02-04T14:21:24-08:00 𝒊  Setting default format to: 'text' …
```
=> feat: Add JSON as a CLI output format (#215)

packages/cdk/lib/constructs/engines/engine.ts, packages/cdk/lib/constructs/engines/miniwdl/miniwdl-engine.ts, packages/cdk/lib/constructs/engines/snakemake/snakemake-engine.ts, packages/cdk/lib/env/context-app-parameters.ts, packages/cdk/lib/stacks/context-stack.ts, packages/cdk/lib/stacks/engines/miniwdl-engine-construct.ts, packages/cdk/lib/stacks/engines/snakemake-engine-construct.ts, packages/cdk/lib/types/engine-options.ts, packages/cli/internal/pkg/cli/context/context_environment.go, packages/cli/internal/pkg/cli/context/manager.go, packages/cli/internal/pkg/cli/context/manager_deploy_test.go, packages/cli/internal/pkg/cli/spec/context.go, packages/cli/internal/pkg/cli/spec/project_schema.json, packages/cli/internal/pkg/cli/spec/project_test.go
We want to be able to specify the filesystem used and the throughput. This allows customers with large numbers of large files to accelerate workflows. Filesystem options are S3 and EFS, with a default of S3 for Cromwell and Nextflow and a default of EFS for MiniWDL. Valid throughput values are 1 to 1024.
I have added a test that checks that the default throughput is set. I have run `./scripts/run-dev.sh` and `agc project validate` with a valid agc-project.yaml and an invalid version containing an invalid filesystem.
**Checklist**
----
=> feat: Implement EFS IOPs specification in Project YAML

site/content/en/docs/Concepts/contexts.md, site/content/en/docs/Concepts/engines.md, site/content/en/docs/Workflow engines/snakemake.md
This change adds snakemake to our documentation.
Tested using Hugo.
```
hugo server -D
Start building sites …
hugo v0.92.1+extended darwin/amd64 BuildDate=unknown
WARN 2022/02/28 12:36:46 .Path when the page is backed by a file is deprecated and will be removed in a future release. We plan to use Path for a canonical source path and you probably want to check the source is a file. To get the current behaviour, you can use a construct similar to the one below:
{{ $path := "" }}
{{ with .File }}
{{ $path = .Path }}
{{ else }}
{{ $path = .Path }}
{{ end }}
Re-run Hugo with the flag --panicOnWarning to get a better error message.
| EN
-------------------+-----
Pages            | 96
Paginator pages …
```
=> docs: Adds snakemake to our online documentation

packages/cdk/lib/constants.ts, packages/cdk/lib/stacks/core-stack.ts, packages/cli/internal/pkg/aws/cfn/get_stack_exports.go, packages/cli/internal/pkg/cli/account_activate.go, packages/cli/internal/pkg/cli/account_activate_test.go, packages/cli/internal/pkg/cli/awsresources/awsresources.go, packages/cli/internal/pkg/mocks/aws/mock_interfaces.go, site/content/en/docs/Concepts/accounts.md
Previously, `account activate` did not recall any existing vpcIds and users had to add it in manually. Now, if a vpcId exists, it will recall and use it in-place of generating a new one. 
Added unit tests as well as linted using `make`. 
**Checklist**
----
=> feat: ensures vpcId is recalled (if available) on account_activate

examples/demo-wdl-project/agc-project.yaml, examples/demo-wdl-project/workflows/hello/hello.wdl, packages/cdk/npm-shrinkwrap.json, packages/wes_adapter/README.md, packages/wes_adapter/amazon_genomics/wes/adapters/MiniWdlWESAdapter.py
#358 
added 1.1 to the list of allowed versions in the `miniwdlWesAdapter`. The miniwdl engine already supports 1.1
* Update `hello.wdl` to declare it's version as 1.1
* Update `agc-project.yaml` to declare it's version as 1.1
* `agc account activate`
* `agc context deploy miniContext`
* `agc workflow run hello -c miniContext`
* Workflow accepted and succeeded
Also check to make sure v1.0 workflows still work.
**Checklist**
----
=> fix: miniwdl wdl1.1support

packages/cli/internal/pkg/cli/logs_workflow.go, packages/cli/internal/pkg/cli/logs_workflow_test.go, packages/cli/internal/pkg/cli/workflow/workflow_status.go, packages/cli/internal/pkg/cli/workflow/workflow_tasks.go, packages/cli/internal/pkg/mocks/manager/mock_interfaces.go, packages/cli/internal/pkg/mocks/wes/mock_interfaces.go, packages/cli/internal/pkg/wes/Client.go, packages/cli/internal/pkg/wes/interface.go, packages/wes_api/client/api_workflow_execution_service_log_extension.go
Issue #, if available: N/A
Currently, AGC does not retrieve the `stdout` and `stderr` URLs referenced by the WES server for a workflow run. The URLs themselves are available in the code, but their content is not fetched and displayed to the user. This can make it hard for the user to debug a workflow run with an engine like Toil (because error logs for individual workflows are not available).
This PR extends the WES API bindings with a method that can fetch the URLs returned with workflow logs, by evaluating them relative to the URL of the document containing them and by properly signing the requests. It also reports these logs on the command line when available. …
=> feat: Download and report WES run log files

packages/cdk/lib/constructs/batch.ts, packages/cdk/lib/roles/nextflow-engine-role.ts, packages/cdk/lib/roles/policies/cromwell-batch-policy.ts, packages/cdk/lib/stacks/engines/miniwdl-engine-construct.ts, packages/cdk/lib/stacks/engines/snakemake-engine-construct.ts, packages/cdk/npm-shrinkwrap.json, packages/cli/internal/pkg/environment/environment.go, packages/engines/miniwdl/Dockerfile, packages/engines/miniwdl/buildspec.yml, packages/engines/snakemake/snakemake.aws.sh
#205 
* Updated IAM policies to ensure all engines have permissions to terminate child tasks
* Updated WES adapter IAM policies to ensure they have permission to terminate engine tasks
* Notified miniwdl-ext author of bug in handling `SIGTERM` and added fixed version to our miniwdl deployment
* Found that snakemake doesn't cancel child tasks when handling `SIGTERM` changed that behavior in our snakemake repo.
For all engines:
1. deploy context
2. run a workflow
3. wait until the workflow spawns child tasks that become queued or running in AWS Batch
4. stop workflow with `agc workflow stop`
5. observe that workflow tasks terminate with the expected status reason and for Batch engine tasks, ensure …
=> fix: ensure workflow engines can and do terminate child tasks when the engine task is stopped by AGC

packages/wes_adapter/amazon_genomics/wes/adapters/CromwellWESAdapter.py
Updates Cromwell to handle exit_code conversion (previously missed on #314)
Steps to reproduce [using cromwell]
```
account activate -c
context deploy -c myContext -v 
workflow run words-with-vowels -c myContext -v
logs workflow words-with-vowels -r <RunId>
```
Returns
**Checklist**
----
=> fix: updates cromwell exit_code

packages/engines/miniwdl/miniwdl.aws.sh, packages/engines/new-engine-template/<engine-name>.aws.sh, packages/engines/nextflow/nextflow.aws.sh, packages/engines/snakemake/snakemake.aws.sh
fixes: https://github.com/aws/amazon-genomics-cli/issues/397
The [manifest file definition allows engineOptions and inputFileURLs to be optional](https://github.com/aws/amazon-genomics-cli/blob/884308fc2b7e00d918c57e8a912957076309dde2/site/content/en/docs/Concepts/workflows.md#manifestjson-structure). When parsed by `jq`, these fields will return `"null"` when not present in the file. This can break launching of the workflow from the head job. I have added `// empty` to the `jq` command, allowing it to return nothing if not present, which will allow the in place null checks to succeed.
**Checklist**
----
*By …
=> fix: Add safety checks in optional manifest fields

packages/cli/internal/pkg/wes/client.go, packages/cli/internal/pkg/wes/client_test.go, packages/cli/internal/pkg/wes/option/workflow_engine_params.go, packages/cli/internal/pkg/wes/wes.go
If the engineOptions attribute is not defined in a workflow MANIFEST.json a literal null is sent as a command line option to the engine.
If the map is empty or null, we will not populate the WorkflowEngineParameters field.
Added tests to ensure nothing is sent across when null or empty map passed.
**Checklist**
----
=> fix: do not set WorkflowEngineParameters when empty

packages/cdk/lib/roles/toil-job-role.ts
This adds the  `s3:GetBucketLocation` permission to those granted to Toil. Without it, running CWL workflows with Toil will produce an error:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/toil/jobStores/aws/jobStore.py", line 704, in _bindBucket
self.s3_client.head_bucket(Bucket=bucket_name)
File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 401, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 731, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An …
```
=> fix: Add s3:GetBucketLocation permission for Toil

packages/engines/toil/README.md
I fixed the instructions for pushing a Docker container for Toil to ECR so they can be followed as written; I'd previously broken them when removing the actual WAS account numbers/names I use.
I also changed the local testing instructions to use a more generic tag without my name in it, and to use Docker container names instead of grep to find the test container while it is running.
I ran through the commands suggested in the file to test them. They worked.
**Checklist**
- N/A I have added unit …
=> docs: Fix shown procedures for Toil Docker

packages/engines/toil/Dockerfile, packages/engines/toil/toil.aws.sh
This uses a Toil that can return a state for a workflow that was run through a previous execution of the server. State is stored in S3 in the persistent AGC bucket, and so lives beyond the lifetime of the Toil server container and beyond the lifetime of the context.
This allows `agc context destroy` or `agc workflow status` to still work even if the Toil container is restarted.
Additionally, since AGC seems to leave workflow entries in DynamoDB even after the context they belong to is destroyed, this will allow `agc context destroy` to work on a context that was created with the same name as a previously destroyed context.
**Description of how …
=> fix: Store workflow state in S3 through restart

packages/cli/internal/pkg/cli/workflow/input.go, packages/cli/internal/pkg/cli/workflow/manager.go, packages/cli/internal/pkg/cli/workflow/workflow_run_test.go, packages/cli/internal/pkg/cli/workflow_run.go, packages/cli/internal/pkg/mocks/storage/mock_interfaces.go, packages/cli/internal/pkg/osutils/utils.go, packages/cli/internal/pkg/osutils/utils_test.go, packages/cli/internal/pkg/storage/input_client.go, packages/cli/internal/pkg/storage/input_client_test.go, packages/cli/internal/pkg/storage/interfaces.go, packages/cli/internal/pkg/storage/storage_client.go
=> fix: input files should be resolved as relative to the location of the inputs JSON file

examples/demo-wdl-project/workflows/words/words-with-vowels.wdl
Updated words with vowels workflow to have a full "scatter - gather shape" so as to give a quick workflow testing most actions that will occur on the infrastructure.
* `agc context deploy myContext` (Cromwell)
* `agc context deploy miniContext` (miniwdl)
* `agc workflow run -c myContext words-with-vowels`
* `agc workflow run -c miniContext words-with-vowels`
**Checklist**
----
=> test: Update words with vowels to have the same "shape" as haplotype caller

packages/engines/toil/buildspec.yml
Ahead of engine build code pipeline ensure toil container tag in `buildspec.yml` matches that in `environment.go`
**Checklist**
----
=> fix: Update toil version in buildspec.yml to match DefautlToilTag 

packages/engines/toil/buildspec.yml
Updated Dockerfile path and include version as Docker build argument
Setup AmazonGenomicsCICDK pipeline with linkages to my AGC fork and published updates to my AGC fork. Observed that Toil engine container built as expected.
**Checklist**
----
=> fix: Correct Dockerfile location and version arg for Toil buildspec.yml

packages/cdk/npm-shrinkwrap.json, packages/cli/internal/pkg/aws/cdk/progress.go
Removed code that caused CDK logs to be shown when `-v (--verbose)` flag has NOT been set.
Account activation and context deployment shows only the progress bouncer:
```
agc account activate
2022-05-13T12:12:28-04:00 𝒊  Activating AGC with bucket '' and VPC ''
Bootstrapping CDK... [o---] 1m18s
Activating account... [o---] 4m16s
88665a2eaed7:amazon-genomics-cli mrschre$ cd examples/demo-cwl-project/
88665a2eaed7:demo-cwl-project mrschre$ agc context deploy myContext
2022-05-13T12:20:06-04:00 𝒊  Deploying context(s)
Deploying resources for context(s) [myContext] [---o] 37m52s …
```
=> fix: UX regressions where CDK logs show when --verbose flag is not used

packages/cli/internal/pkg/environment/environment.go, packages/engines/toil/Dockerfile, packages/engines/toil/buildspec.yml
use a commit of Toil that resolves bug in workflow stop
Custom build of the Toil container
```bash
cd packages/engines/toil
docker build -t toil-agc:latest .
docker tag toil-age:latest 123412341234.dkr.ecr.us-west-2.amazonaws.com/toil-agc:latest
docker push 123412341234.dkr.ecr.us-west-2.amazonaws.com/toil-agc:latest
```
Set environment variables to use custom container on context deploy
```bash
export ECR_TOIL_ACCOUNT_ID=123412341234
export ECR_TOIL_REGION=us-west-2
export …
```
=> fix:bump toil commit

packages/cli/Makefile
* Removed the docker build target as we don't build the CLI as a container and haven't for a long time
* Removed redundant (and incorrect) docs targets as they are now in the top level make and not the `cli` package
`make init && make`
`make start-docs`
**Checklist**
----
=> fix: Removed unused and redundant targets in `packages/cli` make file

packages/engines/toil/Dockerfile, packages/engines/toil/README.md, packages/engines/toil/buildspec.yml, packages/engines/toil/toil.aws.sh
As of https://github.com/DataBiosphere/toil/pull/4166, due to be released in Toil 5.8, Toil will now report tasks in its WES run log output.
Unfortunately, AGC will crash if it sees a task in WES output where the task name does not end in `|` and then an AWS Batch job ID. By default Toil does not apply this transformation to task names, even when running against Amazon Batch, because it really only makes sense to do for AGC. So Toil's server now has a `--wes_dialect` option that can be set to `agc` to force it to adjust task names to meet this constraint.
This PR updates the Toil version that the Toil engine container is set to be built …
=> feat: Support and use Toil 5.8's WES task output

packages/engines/nextflow/Dockerfile
- fix: Install which utility for Nextflow image
Issue #, if available: N/A
[//]: # No change in user experience. The new AL2 image doesn't come with `which` utility anymore. This change installs the `which` utility during Nextflow image build.  
[//]: #  Ran build successfully.
**Checklist**
- [N] If this change would make any existing documentation invalid, I have included those updates within this PR
- [Y] Title of this Pull Request follows Conventional Commits standard: https://www.conventionalcommits.org/en/v1.0.0/
----
*By submitting this pull request, I confirm that my …
=> fix: Install which util for nextflow image

examples/demo-nextflow-project/workflows/words/nextflow.config, packages/cli/internal/pkg/environment/environment.go
fix: update nextflow version environment variable
Even after the recent Nextflow version update to `22.04.3` the image is still being resolved for the older version. Fixing the manifest file to pickup the new version.
Integration tests will be run on this change after merge.
**Checklist**
- [N] If this change would make any existing documentation invalid, I have included those updates within this PR
- [N/A] I have linted my code before raising the PR
- [Y] Title of this Pull Request follows Conventional Commits standard: https://www.conventionalcommits.org/en/v1.0.0/
----
*By submitting this pull request, I confirm that my contribution …
=> fix: update nextflow version environment variable

extras/agc-minimal-permissions/lib/policy-statements.ts
#524 
Reduces `resources` scope to APIG resources in the account and adds tag based condition to 
The generated policy statement is now:
```
...
{
"Condition": {
"StringEquals": {
"aws:ResourceTag/application-name": "agc"
}
},
"Action": [
"apigateway:GET",
"apigateway:POST",
"apigateway:PUT",
"apigateway:DELETE",
"apigateway:PATCH"
],
"Resource": "arn:aws:apigateway:*:581254785006:*",
"Effect": "Allow"
}, ...
```
Working on this issue reveals that this package should be update to CDK v2 and further validated. Tracking in #537 
**Checklist**
- [] If this change would make any existing documentation invalid, I have included those updates within this PR
- [] I have added unit tests that prove my fix is effective or that …
=> feat: reduce permissions related to APIGateway for recommended user role

examples/demo-nextflow-project/workflows/rnaseq/MANIFEST.json, packages/cdk/npm-shrinkwrap.json
fix: Set examples rnaseq pipeline version to 1.2
1.5.2 release
As the Manifest version did not have a explicit version set, when the source repository changed the nextflow version the example workflow broke. So, explicitly setting the rnaseq pipeline version to 1.2 -- the version that worked before.
Installed AGC, deployed and run the workflow manually.
**Checklist**
- [N] If this change would make any existing documentation invalid, I have included those updates within this PR
- [Y] Title of this Pull Request follows Conventional Commits standard: …
=> Set example worklfow, nextflow-io rnaseq to v1.2

packages/cli/internal/pkg/storage/input_client.go, packages/cli/internal/pkg/storage/input_client_test.go
Issue #, if available: https://github.com/aws/amazon-genomics-cli/issues/547
If the inptus.json of a workflow contains empty strings, the workflow will now run and will not crash.
A check is added before uploading a file to S3 that the path is actually a file and not a directory.
Wrote a new unit test. All existing unit test and integration tests pass.
**Checklist**
----
=> fix: AGC run fails when empty strings in inputs.json file

packages/cdk/lib/stacks/engines/cromwell-engine-construct.ts, packages/cdk/lib/stacks/engines/miniwdl-engine-construct.ts, packages/cdk/lib/stacks/engines/nextflow-engine-construct.ts, packages/cdk/lib/stacks/engines/snakemake-engine-construct.ts
Closes #624 
Lambda Functions in CDK, by default, do not create Log Groups at CDK deploy time. Log Groups are typically find-or-created when the Lambda executes for the first time.
HOWEVER, there are certain scenarios where the CloudFormation stack needs to know what the Log Group will be. For example, if the Function's log retention needs to be set to a specific value, or if some other resource needs to know the Log Group's properties.
In THESE cases, CDK will generate a `Custom::LogRetention` resource in the background, intended to set retention and return metadata about a Lambda's Log Group. You guessed it, this Custom Resource is itself a Lambda with a runtime of...drumroll...`nodejs14.x` (at least in CDK `2.50.0`). So that's where our …
=> fix: Comment out Lambda return value to avoid nodejs14.x

README.md, site/content/en/_index.html, site/content/en/docs/Concepts/_index.md, site/content/en/docs/Contribution guidelines/_index.md, site/content/en/docs/Examples/_index.md, site/content/en/docs/Getting started/_index.md, site/content/en/docs/Overview/_index.md, site/content/en/docs/Reference/_index.md, site/content/en/docs/Tutorials/_index.md, site/content/en/docs/Workflow engines/Filesystems/_index.md, site/content/en/docs/Workflow engines/_index.md
adds eol notice
🤞 
**Checklist**
----
=> chore: Eol notice
